image: rustdocker/rust:stable

before_script:
  - apt-get update -qq && apt-get install -y -qq libdbus-1-dev libclang-dev libudev-dev

stages:
    - test
    - build

test:
  script:
    - cargo check #+nightly check --features "clippy"

build:
  only:
    - next
  script:
    - make && make vendor
  artifacts:
    paths:
    - vendor-$(grep -P 'version = "(\d.\d.\d)"' asus-nb-ctrl/Cargo.toml | cut -d'"' -f2).tar.xz
    - cargo-config

variables:
  GIT_SUBMODULE_STRATEGY: normal

